// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentResourceTracker.Data;

#nullable disable

namespace StudentResourceTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004045543_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("StudentResourceTracker.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Math-related resources",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Science resources",
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            Description = "English & literature",
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Coding & software",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 5,
                            Description = "History resources",
                            Name = "History"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Miscellaneous",
                            Name = "General"
                        });
                });

            modelBuilder.Entity("StudentResourceTracker.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StudentId");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedOn = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = 4,
                            Description = "MIT OpenCourseWare — classic algorithms course",
                            IsCompleted = false,
                            StudentId = 1,
                            Title = "Introduction to Algorithms",
                            Type = 3,
                            Url = "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/"
                        },
                        new
                        {
                            Id = 2,
                            AddedOn = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CategoryId = 1,
                            Description = "Khan Academy calculus series",
                            IsCompleted = true,
                            StudentId = 2,
                            Title = "Calculus for Beginners",
                            Type = 1,
                            Url = "https://www.khanacademy.org/math/calculus-1"
                        });
                });

            modelBuilder.Entity("StudentResourceTracker.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Course")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnrolledOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Course = "Computer Science",
                            Email = "alice@example.com",
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            LastName = "Johnson",
                            StudentNumber = "S001"
                        },
                        new
                        {
                            Id = 2,
                            Course = "Mathematics",
                            Email = "bob@example.com",
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bob",
                            LastName = "Smith",
                            StudentNumber = "S002"
                        });
                });

            modelBuilder.Entity("StudentResourceTracker.Models.Resource", b =>
                {
                    b.HasOne("StudentResourceTracker.Models.Category", "Category")
                        .WithMany("Resources")
                        .HasForeignKey("CategoryId");

                    b.HasOne("StudentResourceTracker.Models.Student", "Student")
                        .WithMany("Resources")
                        .HasForeignKey("StudentId");

                    b.Navigation("Category");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentResourceTracker.Models.Category", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("StudentResourceTracker.Models.Student", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
